# Generated by Django 4.0.3 on 2022-03-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_usercatergorylevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=' ', upload_to='media/'),
            preserve_default=False,
        ),
    ]
