# Generated by Django 4.0.3 on 2022-03-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_url',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
